### ISSUE TITLE
weather icon missing

### ISSUE THREAD

**Issue by ghost03x** [closebox73/Leonis#10]
![Screenshot from 2023-01-02 01-11-40](https://user-images.githubusercontent.com/92873829/210182926-98ae3f84-88f7-4c5e-ba23-4b4c86a98problemn769.png)
problem with weather icon and weird 'A^' icon. How to fix this problem?? Im using linux mint 21.1 and shelyak. sorry for my bad english

**Comment by closebox73** [comment]
ahh.. I forgot to update this theme..
open Shelyak.conf then add this line to config ( below font) `override_utf8_locale = true,`
then save

**Comment by ghost03x** [comment]
thank you so much......
![Screenshot from 2023-01-02 17-24-23](https://user-images.githubusercontent.com/92873829/210227918-c11d81f4-ed71-4397-b2fa-5bb912318fc9.png)

**Comment by closebox73** [comment]
I think it's too small compared to your screen 😅

**Comment by ghost03x** [comment]
im using dual monitor rn thats why :)...can u show me how to use mocp in this script?? If you dont mind

**Comment by closebox73** [comment]
I've tried using mocp, but a glitch appears, sometimes the status is blank for a split second, sometimes the status doesn't match.  But if you want to try, I'll make it later👍

**Comment by ghost03x** [comment]
thanks....take your time

**Comment by ghost03x** [comment]
thank you so much
