### ISSUE TITLE
Lua rings don't load.

### ISSUE THREAD

**Issue by vtecek1** [closebox73/Leonis#12]
![Screenshot from 2023-08-02 08-48-35](https://github.com/closebox73/Leonis/assets/128639826/96c3de6d-d149-4293-a9e1-db47f53d1a0c)
I followed the installation guide, but when I run start.sh, says "conky: no process found" then quits. When I run Mimosa.conf it opens, but the lua rings don't work. I get this in terminal:

conky: llua_do_call: function conky_ring_stats execution failed: attempt to call a nil value
No players found
No players found
No players found
No players found

It loops this over and over.

I am on Manjaro Linux.

**Comment by vtecek1** [comment]
Fixed. Didn't have conky-cairo, and my battery is BAT1 not BAT0.

**Comment by closebox73** [comment]
@vtecek1 Sorry github apps didn't show notification about this issue, but thanks for using my theme
