### ISSUE TITLE
Low resolution Box/Box1.png with the Regulus theme

### ISSUE THREAD

**Issue by Oman395** [closebox73/Leonis#6]
Title says it. I'm running a 1080p display and the icons for the dials look very blurry, and the corners are quite severely aliased. Perhaps it looks better on higher resolutions; for now, do you have any higher resolution copies of the same images, or a place I could get the icons and create my own higher resolution version? Thanks!

**Comment by Oman395** [comment]
Almost forgot, here's what they look like (dunno how well it'll get across through github tho)
![image](https://user-images.githubusercontent.com/77183348/178124578-804702b4-d5a0-44a9-a02e-ef8fcc33b43c.png)

**Comment by closebox73** [comment]
actually i'm trying to buy a new laptop with that resolution, but for some reason still not done.. 😂

for the box you can make it yourself using inkscape, while for the weather icon in the current version of regulus I use a text icon ( font) instead of a png image

**Comment by Oman395** [comment]
The issue is more with these icons specifically, b/c the image for them is only 113x113 scaled up to 190x190
![image](https://user-images.githubusercontent.com/77183348/178168390-30e7a284-d23c-4ff3-9465-09f7485fbc0f.png)
![image](https://user-images.githubusercontent.com/77183348/178168434-ff8141a8-1678-4224-9b10-65b65f5c83ac.png)
![image](https://user-images.githubusercontent.com/77183348/178168461-3723a44b-76b8-4a6b-888b-e79dc7fb74d4.png)

**Comment by closebox73** [comment]
I've updated the regulus with a 250x250 box.png resolution, please check on pling.com

😊
