### ISSUE TITLE
usage notification [not a proper issue] 

### ISSUE THREAD

**Issue by dentex** [closebox73/Leonis#7]
I loved the Shelyak themes, so I slightly modified them to better suit my needs. 
https://github.com/dentex/conky_themes
Full credits given. GPLv3 licence included.
I hope you like it. Let me know in case of any issue.

Best regards, 
_dentex_

**Comment by closebox73** [comment]
Wow, they look amazing 😍, but i see just for days and months in italian, why not all of them?  

but I say thank you for using the theme that I made

Best regards
closebox73

**Comment by dentex** [comment]
Thanks to you for the beautiful themes 😊


> ... i see just for days and months in italian, why not all of them?

I think this is based on the system set language. Now i can't check, but I'll let you know.

**Comment by closebox73** [comment]
actually it's up to everyone's taste 😊
